<?php

declare(strict_types=1);

/**
 * Generate a go2rtc configuration from the cameras stored in the CRM.
 * Usage:
 *   php database/go2rtc_config.php [output.yaml]
 *
 * Writes a `go2rtc.yaml` mapping every enabled camera (with an RTSP source)
 * to a stream name. Run go2rtc with it:
 *   go2rtc -config go2rtc.yaml
 *
 * The file contains camera credentials — restrict permissions (chmod 600)
 * and keep it out of version control.
 */

define('ROOT_PATH', dirname(__DIR__));

require ROOT_PATH . '/vendor/autoload.php';

load_env(ROOT_PATH . '/.env');

use App\Core\Database;

$db = Database::connection();

$cameras = $db->query(
    'SELECT id, name, location, rtsp_url, stream_name
     FROM cameras
     WHERE enabled = 1 AND rtsp_url IS NOT NULL AND rtsp_url != ""
     ORDER BY sort_order ASC, id ASC'
);

if ($cameras === []) {
    echo "No enabled cameras with an RTSP source found.\n";
    echo "Add cameras in the CRM first (CCTV page), or set their RTSP URL.\n";
    exit(0);
}

$streams = [];
foreach ($cameras as $cam) {
    $name = trim((string) $cam['stream_name']);
    if ($name === '') {
        $name = strtolower((string) $cam['name']);
        $name = preg_replace('/[^a-z0-9]+/', '_', $name);
        $name = trim($name, '_');
        if ($name === '') {
            $name = 'cam_' . (int) $cam['id'];
        }
    }
    if (!preg_match('/^[a-zA-Z0-9_-]{1,80}$/', $name)) {
        echo "Skipping camera #{$cam['id']} ({$cam['name']}): invalid stream name '{$name}'\n";
        continue;
    }
    $yamlValue = str_replace(['\\', '"'], ['\\\\', '\\"'], (string) $cam['rtsp_url']);
    $streams[$name] = '"' . $yamlValue . '"';
}

if ($streams === []) {
    echo "No valid streams to write.\n";
    exit(0);
}

$target = $argv[1] ?? null;
$path   = $target !== null
    ? (str_starts_with($target, '/') ? $target : ROOT_PATH . '/' . $target)
    : ROOT_PATH . '/go2rtc.yaml';

$lines   = [];
$lines[] = '# Generated by php database/go2rtc_config.php — do not edit manually.';
$lines[] = '# Contains camera credentials: chmod 600 and keep out of git.';
$lines[] = '';
$lines[] = 'streams:';
foreach ($streams as $name => $value) {
    $lines[] = "  {$name}: {$value}";
}
$lines[] = '';

file_put_contents($path, implode("\n", $lines));
@chmod($path, 0600);

echo "Wrote " . count($streams) . " stream(s) to {$path}\n";
echo "Run: go2rtc -config " . basename($path) . "\n";
echo "Then point the CRM's CCTV page at the go2rtc address (default http://127.0.0.1:1984).\n";